site/styles/_carousel.scss

- This was in commit d0530ce0aeb924da353cca5f6e1e6aaf9c0552b4 into indiereign/shift72-abc, which subsequently went awol
- Will need to be replicated into shift72-abc
viz: https://github.com/indiereign/shift72-abc/commit/d0530ce0aeb924da353cca5f6e1e6aaf9c0552b4

Centering carousel images

---

site/templates/nav.jet

support search_disabled config

---

site/templates/nav.jet
site/templates/nav/user_logged_in.jet
site/templates/nav/user_logged_out.jet

& hide library link if 'library_disabled' is true

Split nav into multiple templates

---

site/styles/_meta-detail.scss
site/templates/collection/carousel.jet
site/templates/items/featured_item.jet
site/templates/items/meta_item.jet

Fixes: [SH-5562](https://indiereign.atlassian.net/browse/SH-5562)

Show year in title

---

site/templates/collection/carousel.jet
site/templates/collection/carousel_item.jet

Sepearate carousel slides into its own template, so we dont have to redo the whole thing if someone wants a change.

Split carousel

---

site/templates/page/homepage.jet

support any links from other s72 apps that link to specific content pages

SH-5530 support hashbang links

---

site/static/js/main.js
site/styles/_swiper.scss
site/templates/collection/slider.jet

Porting PR from https://github.com/indiereign/shift72-abc/pull/32 - see that for description.

5476 swiper arrows

---

package.json
site/classifications.all.json.jet
site/templates/items/meta_item.jet
site/templates/items/tagline.jet

- Upgrade kibble
- Add tv seasons classifications to classifications.all.json
- Extend tagline.jet to take a classifications option (defaults to true)
- Don't show classifications on partials

SH-5654 Classifications on tv seasons

---

kibble.json
package-lock.json
package.json

Did I do this right?
Also... I couldn't recreate the error for some reason.

change kibble version

---

site/it_IT.all.json

Just missing the playback window message for the player... I can't figure out where that one is hidden (not in core-template/relish/the player)!

AB#561 more IT language variables

---

site/static/js/main.js
site/styles/_icons.scss
site/templates/nav.jet

No more error in console.  X icon works like the one on Lonely Planet.

fixed hamburger bug

---

kibble.json
site/de_DE.all.json
site/es_ES.all.json

Obviously heaps of stuff missing.

AB#562 add german and spanish

---

site/en_AU.all.json

I've added all of the i18n strings from Relish that I can find and put TODO in places where I don't know what the value should be.  I'm guessing those should all be filled out before this gets merged... but they had no default values in Relish so maybe it's not a big deal.

More language vars

---

site/styles/_meta-detail.scss

AB#606 fixed episode play button padding

---

site/styles/_pages.scss
site/templates/film/item.jet
site/templates/items/bonus_item.jet
site/templates/tv/detail.jet

This just stops images on content pages from being super wiiiiiiiiiiiide on mobile.

Ab#801 large images cause mobile scrolling horizontally

---

site/styles/_pages.scss

AB#610 Removed max width from collection css

---

site/styles/_meta-detail.scss
site/templates/tv/detail.jet

- Removed `d-flex` class from the main div.
- Replaced `slider` with `list`.
- Added css from the `faclon`

bonus content fix

---

site/el_EL.all.json

Added from [this](https://docs.google.com/spreadsheets/d/1NW_9dZAoDA4JAeinSJokc_hUnIc3X6Cc3nIxS_Y6VVg/edit#gid=1322327829) document.

Greek translations

---

site/styles/main.scss

ADO: [Click here](https://dev.azure.com/S72/SHIFT72/_workitems/edit/838/)

fix long string wrapping issue

---

site/en_AU.all.json

Also show a nicer message if IP throttled after too many failed attempts.
In preparation for a relish release (1.3.33).

Show suspended message instead of redirecting

---

kibble.json
site/no_NO.all.json

Added Norweigian translations based on [this](https://docs.google.com/spreadsheets/d/1mkVEkNBuXPgCOzYe0wh0vafQn9dEchC5r4qBvuFL5d4/edit#gid=1668931288) file.

add norweigian translations

---

site/static/js/main.js

Bumps the whole page down by nav-item height if the subnav wraps.  Bumps it back up if the subnav unwraps.

increases page padding when subnav wraps

---

site/styles/_forms.scss
site/styles/main.scss

Based on [this card](https://dev.azure.com/S72/SHIFT72/_workitems/edit/1443)

improve modal container design

---

site/styles/_meta-detail.scss

fixed gradient issue for detail background images

---

site/styles/_forms.scss

I can't find a reason for that margin to be 0... maybe something will come up in testing?

fixed modal alignment issue

---

site/en_AU.all.json
site/styles/_pin-codes.scss
site/styles/_shift72.scss
site/styles/_variables.scss
site/styles/main.scss

- pin code-specific CSS changes in _pin-codes.scss
- user account form changes in _shift72.scss
- variable for spacing buttons in the modal in _variables.scss
- include _pin_codes.scss in main.scss (and some whitespace changes)

CSS fix for new My Account layout

---

site/manifest.json.jet

Included code for icons-512 in the manifest file which would help us to not copy/paste into a new site each time.

Add code for icons-512

---

site/forgotpassword.html.jet
site/styles/_forms.scss

I can't actually test that this works (Ubuntu)... would one of you mind checking that it's okay before I merge please.

ie11 password reset justify bug fix

---

site/styles/_variables.scss

Based on [this task](https://dev.azure.com/S72/SHIFT72/_workitems/edit/2160/) where the navigation was jumping up/down on page load for the desktop view.

fix page jump in navigation

---

kibble.json
site/pl_PL.all.json

I have tested the language file and it is working.

added polish language

---

site/styles/_buttons.scss
site/styles/_carousel.scss
site/styles/_collections.scss
site/styles/_footer.scss
site/styles/_forms.scss
site/styles/_meta-detail.scss
site/styles/_mixins.scss
site/styles/_nav.scss
site/styles/_shopping.scss
site/styles/_social-media-buttons.scss
site/styles/_variables.scss
site/styles/main.scss

This is the light theme moved from shift72-style-template with some additions. You can switch from light-theme to dark-theme using `$var-text` and `$var-background`.

Light Theme

---

site/styles/_pages.scss

Here is the ADO card: (https://dev.azure.com/S72/SHIFT72/_boards/board/t/Delivery%20team/Stories/?workitem=2712)

form header alignment fix

---

site/styles/_footer.scss
site/styles/_meta-detail.scss

https://dev.azure.com/S72/SHIFT72/_workitems/edit/2713/

Ab#2713 bugs

---

site/styles/_language-selector.scss

Just changed the cursor to be consistent with the other dropdown menus.

changed cursor on language selector

---

site/styles/_pages.scss

Aligned background to the right to resolve the issue found in this task: (https://dev.azure.com/S72/SHIFT72/_boards/board/t/Delivery%20team/Stories/?workitem=2870)

Curated pages background

---

site/styles/_buttons.scss
site/styles/_shift72.scss

added border-radius of 4px to all buttons to be consistent 
[ADO card](https://dev.azure.com/S72/SHIFT72/_workitems/edit/3943)

Input radius onto all buttons

---

site/styles/_pages.scss

Current State:
- Content goes full screen size width
Ideal State:
- Set a max-width
ADO card -> https://dev.azure.com/S72/SHIFT72/_workitems/edit/3970

set max-width to content pages

---

site/styles/_availability-tags.scss
site/styles/_buttons.scss
site/styles/_carousel.scss
site/styles/_collections.scss
site/styles/_footer.scss
site/styles/_forms.scss
site/styles/_homepage.scss
site/styles/_meta-detail.scss
site/styles/_meta-item-tagline.scss
site/styles/_meta-item.scss
site/styles/_nav.scss
site/styles/_pages.scss
site/styles/_search.scss
site/styles/_shift72.scss
site/styles/_shopping.scss
site/styles/_social-media-buttons.scss
site/styles/_variables.scss
site/styles/_wishlist.scss
site/styles/main.scss
site/templates/application.jet

- changed font family to Poppins -> [ADO card](https://dev.azure.com/S72/SHIFT72/_workitems/edit/3965)
- changed the font-weight based on the [proposed style ](https://zpl.io/bW8k39M)

3965 New Font

---

site/it_IT.all.json

update missing translation

---

site/styles/_can-be-watched-button.scss

https://dev.azure.com/S72/SHIFT72/_workitems/edit/4369
Hotfix into main since the event button will be added to 2 more sites shortly.  Ideally all sites that have the event button should be moved to npm core-template (10 sites total).

fix(styling): event button in page collection item now stacks vertically

---

CHANGELOG.md
package.json

Release 0.1.0 alpha.4

---

CHANGELOG.md
package.json

Release 0.1.0-alpha.4

---

CHANGELOG.md
package.json

0.1.0-beta.2

---

site/styles/_meta-detail.scss
site/templates/bundle/background.jet
site/templates/bundle/buttons.jet
site/templates/bundle/extras.jet
site/templates/bundle/item.jet
site/templates/bundle/list.jet
site/templates/bundle/synopsis.jet
site/templates/bundle/tagline.jet
site/templates/bundle/title.jet

replaced bundle page HTML
replaced bundle page CSS
atomised bundle page jets to reduce impact of client customisation

feat(improvements): bundle page redesign

---

site/styles/_cookie-consent.scss
site/styles/_variables.scss

Stored the links in variables in case if it needs to be changed. For ex, a client might have light primary and secondary color and since the banner bg is white it might not be visible.

added link and hover link color in variable

---

kibble.json
site/zh_TW.all.json

Can we squeeze this in before the next core release?

Add Taiwanese Chinese language file

---

CHANGELOG.md
package.json

- Nav vertical line margins now on both sides.
- Modal trailer margins.

release-0.3.2

---

CHANGELOG.md
kibble.json
package-lock.json
site/ca_ES.all.json

https://dev.azure.com/S72/SHIFT72/_workitems/edit/5690/

Ab#5690 catalan translations

---

CHANGELOG.md
site/styles/_nav.scss

Use the right logo size variable in the right breakpoint

Choose the right width for md/lg logos

---

site/ar_LB.all.json
site/ca_ES.all.json
site/da_DK.all.json
site/de_DE.all.json
site/ee_EE.all.json
site/el_EL.all.json
site/en_AU.all.json
site/es_ES.all.json
site/es_MX.all.json
site/fi_FI.all.json
site/fr_FR.all.json
site/hr_HR.all.json
site/hu_HU.all.json
site/it_IT.all.json
site/ja_JP.all.json
site/lt_LT.all.json
site/nl_BE.all.json
site/no_NO.all.json
site/pl_PL.all.json
site/pt_BR.all.json
site/pt_PT.all.json
site/ru_RU.all.json
site/se_SE.all.json
site/tr_TR.all.json
site/uk_UA.all.json
site/zh_TW.all.json

Adds support for too many requests error from recently added rate limiting on `/account_exists `

too many requests i18n support

---

CHANGELOG.md
package.json
site/templates/page/page-content.jet

Release 0.4.0 rc.0

---

site/ar_LB.all.json
site/ca_ES.all.json
site/da_DK.all.json
site/de_DE.all.json
site/ee_EE.all.json
site/el_EL.all.json
site/en_AU.all.json
site/es_ES.all.json
site/es_MX.all.json
site/fi_FI.all.json
site/fr_FR.all.json
site/hr_HR.all.json
site/hu_HU.all.json
site/it_IT.all.json
site/ja_JP.all.json
site/lt_LT.all.json
site/nl_BE.all.json
site/no_NO.all.json
site/pl_PL.all.json
site/pt_BR.all.json
site/pt_PT.all.json
site/ru_RU.all.json
site/se_SE.all.json
site/tr_TR.all.json
site/uk_UA.all.json
site/zh_TW.all.json

- New language string for `shopping_complete_plan`
- Fix typo in English translation for `shopping_card_new_subscription`

AB#6500 some translations for festival passes

---

site/ar_LB.all.json
site/ca_ES.all.json
site/da_DK.all.json
site/de_DE.all.json
site/ee_EE.all.json
site/el_EL.all.json
site/en_AU.all.json
site/es_ES.all.json
site/es_MX.all.json
site/fi_FI.all.json
site/fr_FR.all.json
site/hr_HR.all.json
site/hu_HU.all.json
site/it_IT.all.json
site/ja_JP.all.json
site/lt_LT.all.json
site/nl_BE.all.json
site/no_NO.all.json
site/pl_PL.all.json
site/pt_BR.all.json
site/pt_PT.all.json
site/ru_RU.all.json
site/se_SE.all.json
site/templates/application/application.jet
site/tr_TR.all.json
site/uk_UA.all.json
site/zh_TW.all.json

- Adds `<s72-donate-button />` right before closing `</body> tag
- It must be in this spot to ensure it is over pretty much everything (with few exceptions like mobile menu)
- Translations

add donate button and translations

---

site/ar_LB.all.json
site/ca_ES.all.json
site/da_DK.all.json
site/de_DE.all.json
site/ee_EE.all.json
site/el_EL.all.json
site/en_AU.all.json
site/es_ES.all.json
site/es_MX.all.json
site/fi_FI.all.json
site/fr_FR.all.json
site/hr_HR.all.json
site/hu_HU.all.json
site/it_IT.all.json
site/ja_JP.all.json
site/lt_LT.all.json
site/nl_BE.all.json
site/no_NO.all.json
site/pl_PL.all.json
site/pt_BR.all.json
site/pt_PT.all.json
site/ru_RU.all.json
site/se_SE.all.json
site/tr_TR.all.json
site/uk_UA.all.json
site/zh_TW.all.json

Added missing translations to each language (missing keys are using the English translations ), removed duplicate translations

Update language files

---

site/styles/_buttons.scss

primary-scss-to-css-variable

---

CHANGELOG.md
package.json

update version / changelog for 0.4.4

---

site/styles/_pages.scss

[ADO](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=6606)
(Content) pages don't need minimum heights anymore

AB#6606 Remove minimum page heights

---

scripts/translate.mjs

Google translate doesn't handle blank strings or spaces too well not allowing the key to get set, so as a quick fix, just check if the string is blank and set the value for the key accordingly.

Updated auto translate to handle blank values and spaces.

---

site/styles/_forms.scss

[AB#6609](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/6609) Changed opacity for form borders to make text boxes more visible

form border opacity change

---

site/templates/tv/detail.jet

Doing Div audit, I don't think these are needed, please double check me

</div> removal

---

site/static/js/main.js
site/templates/application/application.jet

Supporting work for [this PR](https://github.com/indiereign/shift72-web/pull/284)
This work is to support the [SVOD customer journey](https://dev.azure.com/S72/SHIFT72/_workitems/edit/6124) work. The intention is to provide a way to request the route for a slug without having to hit the APIs

add urlMapService

---

CHANGELOG.md
site/styles/_meta-detail.scss
site/styles/_pages.scss
site/styles/_variables.scss

ADO card: ☑️ [AB#8092](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/8092)
Designs: 
- 📱 [Mobile](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142ba7e15e60023340022d8)
- 📱 [Mobile with sponsor image](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142ba83fd3fd250f50e6216)
- 💊 [Tablet](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142baea05f63b262914e788)
- 💊 [Tablet with sponsor image](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142baeda13fc726053e405a)
- 🖥 [Desktop](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142bb2aceca8924c0b76f62)
- 🖥 [Desktop with sponsor image](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142bb2eb8582a2b4c2c93ee)
- Changes height …

Implement designs 8092 - adjust poster and spacing below nav

---

CHANGELOG.md
site/ar_LB.all.json
site/ca_ES.all.json
site/da_DK.all.json
site/de_DE.all.json
site/el_EL.all.json
site/en_AU.all.json
site/es_ES.all.json
site/es_MX.all.json
site/et_ET.all.json
site/fi_FI.all.json
site/fr_FR.all.json
site/hr_HR.all.json
site/hu_HU.all.json
site/it_IT.all.json
site/lt_LT.all.json
site/no_NO.all.json
site/pl_PL.all.json
site/pt_BR.all.json
site/pt_PT.all.json
site/ru_RU.all.json
site/tr_TR.all.json
site/uk_UA.all.json
site/zh_TW.all.json

ADO card: ☑️ [AB#9439](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9439)
Standardise on "CVC" rather than "CVV" as per Stripe's preference

AB#9439 Translations

---

site/styles/_availability-tags.scss
site/styles/_awards.scss
site/styles/_meta-detail.scss
site/styles/_meta-item-tagline.scss
site/templates/tv/detail.jet

ADO card: ☑️ [AB#8089](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/8089)
This card implements spacing feedback from design as per annotated images in [this google doc](https://docs.google.com/document/d/1EJlDKaCQ7PIDVE3P_dPo6e765CkYVQPZro7v4m9FEgQ/edit#heading=h.51usj6fb9f8h)

Ab#9013 spacing between components

---

site/el_EL.all.json
site/et_ET.all.json
site/fi_FI.all.json
site/fr_FR.all.json
site/it_IT.all.json
site/ja_JP.all.json
site/lt_LT.all.json
site/no_NO.all.json

Rach pointed out a few dodgy live lozenge translations so I've done a "best guess" fix.

live lozenge translation fixes

---

CHANGELOG.md
kibble.json
package-lock.json
package.json
site/templates/application/application.jet

Patch release 1.5.1 to fix relish version to 1.3 from latest

Release 1.5.1

---

site/styles/_availability-tags.scss
site/styles/_carousel.scss

ADO card: ☑️ [AB#9795](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9795)
Fixed Live Lozenge width on iPad Air 2 iOS 13.  Also ran the linter.

fixed lozenge width + lint

---

site/en_AU.all.json

ADO card: ☑️ [AB#9944](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9944)
Reflect the changes to the default messaging in shift72-web in the language file as well. 
Q: Do we want to update other languages as well?

AB#9944 Fix wording in lang file

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

- [AB#9564](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9564) Live label to film detail page and carousel with translations.
- [AB#9361](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9361) Translations for live events, poster live availability status styling changes
- Translations for live event purchase flow.
- Translations for credit card validation errors.
- Translations for new card timing out error.
- Award categories moved to above film description
- Inline cta buttons now grow when text is wider than button width.
- TV season detail page layout now matches film detail page layout.
- Trailer autoplay disabled for CTA buttons in homepage carousel.
- Gap below page-collections consistent with sliders
- Made …

1.6.0 changelog

---

CHANGELOG.md
site/styles/_awards.scss
site/styles/_cta-buttons.scss

ADO card: ☑️ [AB#10080](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/10080)
fix firefox button squashing

fix firefox button squashing

---

.github/workflows/pages.yml
site/styles/_availability-tags.scss
site/styles/_awards.scss
site/styles/_cta-buttons.scss
site/styles/_meta-detail.scss
site/styles/_meta-item-tagline.scss
site/styles/_meta-sub-item.scss
site/styles/_swiper.scss
site/styles/_typography.scss
site/styles/_variables.scss
site/templates/film/item.jet

ADO card: ☑️ [AB#10098](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/10098)
Elab notes/AC: 📃 [Google Docs](https://docs.google.com/document/d/1UrEIFVuw24Gm_jjW-5g2ifCVLZE4lpomaGQ2rfQ6Up0/edit)
Have been going through the spacing with design team. This PR contains all their adjustments. See google doc for details.

Ab#10098 core template spacing adjustments from design

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

- Bonus content and episode show/hide component.
- Modified powered_by_url translations.
- Various spacing style changes.
- Pricing buttons no longer get squashed in Firefox.
- Spacing issues on small screens.

Release 1.7.0

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

- Configuration to change or remove the forgot password link
- Configuration to change or remove the my account link
- Styling for SSO buttons
- CSS variables for change default button colors
- linkedin social link
- Nav mobile top padding to meet design spec
- Social link redesign
- GA4 tracking of ecommerce data
- Form control styling bug in 1.9.1

1.9.2 + changelog

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

Release 1.9.3

---

.editorconfig
site/styles/_collections.scss
site/styles/_swiper.scss
site/styles/_variables.scss
site/templates/collection/slider-buttons.jet
site/templates/collection/slider.jet
site/templates/collection/wishlist.jet
site/templates/film/item.jet
site/templates/tv/detail.jet

Refactor slider buttons to undo repeated code and allow for better default styling / color overides in shared templates.

AB#11608 refactor slider buttons

---

CHANGELOG.md
site/plans.html.jet
site/styles/_footer.scss
site/styles/_plans.scss

[AB#11670](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11670) plans page alignment / layout fix

Ab#11670 plans page alignment / layout fix

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

Release 1.9.7

---

CHANGELOG.md
kibble.json
package-lock.json
package.json
site/styles/_footer.scss
site/styles/_plans.scss

Release 1.9.8

---

kibble.json
package-lock.json
package.json

prep release 1.9.8

---

site/styles/_shift72.scss

I must have changed a bunch of css classes but not nuked cache at some point :/

fix up css issues with delete ui

---

site/ar_LB.all.json
site/ca_ES.all.json
site/da_DK.all.json
site/de_DE.all.json
site/el_EL.all.json
site/en_AU.all.json
site/es_ES.all.json
site/es_MX.all.json
site/et_ET.all.json
site/fi_FI.all.json
site/fr_FR.all.json
site/hr_HR.all.json
site/hu_HU.all.json
site/it_IT.all.json
site/ja_JP.all.json
site/lt_LT.all.json
site/nl_BE.all.json
site/no_NO.all.json
site/pl_PL.all.json
site/pt_BR.all.json
site/pt_PT.all.json
site/ru_RU.all.json
site/sr_SR.all.json
site/tr_TR.all.json
site/uk_UA.all.json
site/zh_TW.all.json

Translation changes for the form UI change made in https://github.com/indiereign/shift72-web/pull/44

translations for the new user delete confirmation modal

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

Release our new user self deletion stuffs

Release 1.9.10

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

Adds new Checkout links to config.

Release 1.9.11

---

site/templates/application/application.jet

This change uses the new flatter options object as well as language provider.

Support new checkout options object

---

CHANGELOG.md
kibble.json
package.json

Prep release 1.9.13

---

CHANGELOG.md
package-lock.json
package.json
site/templates/common/cta_buttons.jet

release 1.9.14

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

release 1.9.15

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

prepare release 1.9.20

---

CHANGELOG.md
kibble.json
package-lock.json
package.json

release 1.9.23
