- site/google.jet
- don't load Google Tag Manager and/or Google Analytics unless the site doesn't require a cookie to be agreed-to, or the cookie is set
- merge two blocks into a single `GoogleScripts` block in google.jet; will need application.jet updated to include this consolidated block
- Requires v1.3.19 of Relish so a/ hasCookieConsent is available to run and b/ message bus notice 'cookie-consent-set' can be listened-for
> Don't load GTM or Google Analytics unless cookies are accepted

- site/styles/_footer.scss
So it never gets split over multiple lines (leave that up to the copyright notice and nav)
> flex-shrink: 0 for the 'Powered by Foo' badge in the footer

- site/styles/_footer.scss
- site/templates/footer.jet
- site/templates/footer/powered-by.jet
Stop text wrap when footer links are larger than expected.
Split into separate template so easier to change.
Note usage of `{{include "footer/powered-by" }}` instead of previous combo of `{{ import... }}` and `{{yield ...() }}`.
Seems a bit easier to manage.
> Powered by

- site/en_AU.all.json
- site/styles/_meta-detail.scss
- Support for size-specific labels e.g "country" vs "countries" rather than "country(s)"
- CSS for countries label
> Support for countries on item.jet

- site/templates/collection/carousel_item.jet
- site/templates/film/item.jet
- site/templates/items/featured_item.jet
- site/templates/items/meta_item.jet
`film.ReleaseDate` is not nullable, so the default value is `0001-01-01`. This is not accurate.
> only show release year if its at least 1 year after jesus was born

- site/en_AU.all.json
- site/templates/nav.jet
- Added an `aria-label` for the nav search and i18n'd the button (recent Relish change will also use this key).
- Removed a dupe `signup_form_name` (appears 4 lines above it).
> SH-5628 a11y for Search

- site/styles/_nav.scss
- site/templates/nav.jet
- Sub-nav dropdowns were missing right padding.
- Standardised the whitespace.
- Removed a check for `{{if len(site.Navigation.Header) > 0 && showSubNav}}` that was already checked in the outer block.
- And the main point of this was to wrap the `<s72-dropdown>` in a `<li>` for a11y.
Individual commits to aid reviewing the above.
> 5628 a11y sub nav

- site/en_AU.all.json
- site/it_IT.all.json
Added a missing translation for `shopping_error_discount_already_redeemed`.
Note, this looks to be a duplicate for `shopping_error_discount_used_previously`, so I'm wondering if it was a rename of that property or something as I can't see `discount_used_previously` getting returned from the API.
> SH-5475 i18n Promo code already redeemed

- site/templates/collection/carousel_item.jet
- site/templates/film/item.jet
This prevents classification label double ups on carousel and film detail page
> AB#563 removed extra classification labels

- site/de_DE.all.json
ADO card: https://dev.azure.com/S72/SHIFT72/_workitems/edit/1332/
The site is https://online.hardline-festival.de/ and not Hamburg. Looks like {{.Expiry}} tag was showing up in the "Expired' translation. If I am not wrong, the date shouldn't be showing up and hence removed the tag. Verified it using the English translation for staging-abc and just the "expired" tag was showing up without any date.
> fix expired translation bug

- site/static/js/main.js
- site/templates/collection/wishlist.jet
This bug is an unexpected side-effect of adding rollup.js.
The script in the wishlist file was trying to call the `initializeSwiper` function which now get encapsulated by rollup so was causing an error.  I've fixed it by moving the wishlist code into main.js (and checked that there are no similar problems elsewhere).
I think all shift72-template sites that have been created since I did the ES6 stuff will need core updating after this is merged.
> AB#1620 moved wishlist script into main.js

- site/it_IT.all.json
The `signup_terms` and` combined_auth_terms` in it_IT.all.json was missing "/" at the end of the terms and conditions link which was resulting into 404 not found for some of the sites.
> add "/" to missing terms and conditions link

- site/styles/main.scss
Based on [this](https://dev.azure.com/S72/SHIFT72/_workitems/edit/1598/) card. I think I had made this fix couple of months ago for headings, paragraphs, etc. Just included .title in this which would wrap the over flowing text.
> Include title in the fix for long strings

- .gitignore
- package.json
- scripts/language-file-to-csv/language-file-to-csv.js
- scripts/language-file-validator.js
Outputs an up-to-date language CSV which can be imported into Google Sheets using '~' as the separator.
Filters out language vars that don't have a value yet (subscription and pin code related stuff that we haven't used).
The idea here is to be able to quickly give the most up-to-date list of translations to Todd in a format 90% of the way to being presentable to a new client.  Thoughts @stajs @l0ud0gg?
> Language file to CSV script

- site/styles/_shift72.scss
Don't increase the font size or padding of read-only fields when they are text fields (not masked "****" fields)
This is with reference to when dates of birth aren't editable
> Adjust font size of disabled text fields

- site/de_DE.all.json
- site/ee_EE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/fr_FR.all.json
- site/hu_HU.all.json
- site/no_NO.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/tr_TR.all.json
I don't think doing this will upset anyone given that this key is used by a bugged function in Relish.
> removed 'next' word from 'datetime_next' lang vars

- site/static/js/main.js
Based on [this](https://dev.azure.com/S72/SHIFT72/_workitems/edit/2655/) issue. Looks like the overflow was happening due to offset height being added in the subnavOverflowing function. This might not be required anymore since couple of weeks ago the default padding was adjusted in the variable file.
> remove offset height from padding

- site/robots.txt.jet
- site/sitemap.xml.jet
Graham reckons we probably switched to `.xml` in that robots_enabled file for a client so the best solution here is probably to add support for `.xml` and `.txt` in core-template.
> Ab#3099 sitemap xml

- site/google.jet
Let's try again!
Just adding the title to the GTM iframe since that's the only one we can fix cleanly.  The Stripe iframes shouldn't cause an issue for screen readers because they have aria-hidden.  And I haven't been unable to get any of the iframes flagged as an issue using Axe, IBM Equal Access, or SiteImprove.... the only place that says the iframe titles are an issue is [this page](https://my2.siteimprove.com/Accessibility/1002728/Issues/Index?LoadPersonalFilters=True) from Neville but I can't figure out where that page exists on the site or how it came to be... visiting the Accessibility Issues list via the side menu gives you an issue list that does not contain the iframe title issue.
> Added title attribute to GTM iframe

- site/templates/common/social-media-buttons.jet
https://dev.azure.com/S72/SHIFT72/_workitems/edit/4146
I think it's a bit overkill to use title and aria-label but TIFF asked for it specifically because it is recommended on the Font Awesome accessibility page.
> better screenreader support and tooltips for social media buttons

- site/404.html.jet
- site/en_AU.all.json
- site/templates/collection/carousel.jet
- site/templates/page/curated.jet
- site/templates/page/homepage.jet
- site/templates/page/landing.jet
https://dev.azure.com/S72/SHIFT72/_workitems/edit/4153
- Swapped the h2 headings on 404 and landing pages for h1 headings.
- Added h2 headings to collection blocks to avoid skipping from h1 page heading to h3 collection item headings.
> Ab#4153 heading alerts

- site/styles/_nav.scss
- site/styles/_variables.scss
The search bar's md left value was lowered when the new placeholder logos were added.  This means that 2x client logos overlap the search bar in md sized windows.  These new variables provide a quick and easy way to change the search bar position on client sites without needing to manually override the css.
As much as I dislike adding new variables, this seems like the easiest way to solve this problem while we get the new nav sorted.
> feat: added variables for search bar left position

- site/templates/bundle/partial.jet
https://dev.azure.com/S72/SHIFT72/_workitems/edit/4153?src=WorkItemMention&src-action=artifact_link
'Fixes' the bundle title header that shows in search results.
TBH this fix is sidestepping the issue because it just stops the header from showing (I don't think any clients have this config on anyway).  But this brings the bundle partial in line with the other partials... SiteImprove couldn't see them with the config off.
We can come back to this later for a redesign!
> fix(accessibility): added missing config check to bundle partial title

- site/en_AU.all.json
- site/styles/_forms.scss
The flex items were not shrinking because they had their width set to auto. This was pushing them off the screen. The day and year are set to `flex-shrink: 0` to stop them from shrinking so much that they cut off the text inside. This leaves the month which shrinks instead.
Here's the card: https://dev.azure.com/S72/SHIFT72/_boards/board/t/Delivery%20team/Stories/?workitem=4525
> fixed datepicker on small screens

- site/styles/_collections.scss
https://dev.azure.com/S72/SHIFT72/_workitems/edit/4095
> fix: hover preview text for content pages is now center aligned

- site/styles/_meta-item-tagline.scss
- site/templates/items/tagline.jet
https://dev.azure.com/S72/SHIFT72/_workitems/edit/3852
Decided to have another look at this task.  The mystery margin was caused by the first `<li>` containing an empty `<s72-classification-label>`... not exactly sure why it was doing that but I suspect something to do with the Bootstrap list item styles.  Fixed by changing from an `<ul>` to a `<div>` full of `<span>`.
Pro-tip: hide whitespace changes to make the jet diff easier to understand.
> fix: changed tagline from <ul> to <div> to fix hidden margin issue

- site/styles/_language-selector.scss
https://dev.azure.com/S72/SHIFT72/_workitems/edit/4735
Looks like the new nav has a slightly different approach to focus rings than the old nav so the language selector styles needed a little tweak.
> fix: added focus ring to language selector

- package.json
- site/templates/collection/carousel_item.jet
- site/templates/items/featured_item.jet
- site/templates/items/meta_item.jet
- site/templates/page/partial.jet
- This PR updates to the latest kibble which has a template method that strips html tags
- Here's [the card](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Core%20team/Stories/?workitem=4407)
- Basically, clients have assumed they can add HTML to the 'Short description' field in admin, because they can do so in the synopsis below it.
> latest kibble version, stripHTML method on tagline

- CHANGELOG.md
- rollup.config.js
Might be a good idea to test this on your machines before approving to make sure it really works.
> fix: prevent rollup.js from clearing console output when rebuilding

- CHANGELOG.md
- kibble.json
- package.json
- Added Croatian (`hr_HR`) translations file.
- The sign out button can now be selected with keyboard controls.
- Prevent rollup.js from clearing console output when rebuilding.
- Headed banner height replaced with min-height.
- Removed hardcoded English minutes reference in tagline.
- Changed from Node Sass to Dart Sass.
- Improved linter rule sets.
- Major refactor of JS and SCSS files.
- Subnav dropdown width increased for mobile.
> 0.3.0 beta.1

- CHANGELOG.md
- site/templates/items/meta_item.jet
Have added stripHTML to meta item
Checked various places across the site and haven't seen issues elsewhere
> AB#4821 unescaped html tags in kibble template

- CHANGELOG.md
- package-lock.json
- package.json
- Genre limit on meta-item-tagline now works again.
- Typo in English translations file.
> Release 0.3.8

- site/templates/items/tagline.jet
As requested by design - change order of tagline info so it goes duration -> genre -> year
Card [here](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Core%20team/Stories/?workitem=4976)
> move genre after duration in tagline

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/ee_EE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/se_SE.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
This PR adds all the share button related translation phrases:
"social_media_buttons_facebook"
"social_media_buttons_twitter"
"social_media_buttons_linkedin"
"social_media_buttons_email"
"social_media_buttons_email_subject"
"social_media_buttons_copied_link"
"social_media_buttons_copy_link"
> translations for share modal

- CHANGELOG.md
- site/templates/page/content.jet
[USER STORY 5870 Template change to support header image on content page(s)](https://dev.azure.com/S72/SHIFT72/_workitems/edit/5870/)
[AC Google Doc](https://docs.google.com/document/d/1GBPVBiCEaF0NorQ0lPvGakW7nirrevRUo5WUWIIjHUk/edit#heading=h.ygly7pwv59is)
> Add a background image to the page content jet template

- site/templates/tv/detail.jet
TV seasons have been broken as of 0.4.0 due to some unintended code being left in from a previous merge and revert around engagement icons: 
[Initial Merge](https://github.com/shift72/core-template/commit/74e5195b4a2ef3de0b3f82f31363fd27d3dfed77#diff-685e2c69e0cd5ba9d30c38583488cee9e801c82585ab4faa6ccf3f49195d84a3)
[Reverting merge](https://github.com/shift72/core-template/commit/16be9cfce87b16366d7136367948f3c64cb0dde3#diff-685e2c69e0cd5ba9d30c38583488cee9e801c82585ab4faa6ccf3f49195d84a3)
Looks like code was copy pasted instead of removed
> Removed broken tv season divs

- site/styles/_buttons.scss
- site/styles/_can-be-watched-button.scss
- site/styles/_carousel.scss
- site/styles/_meta-detail.scss
- site/styles/_wishlist.scss
- site/templates/bundle/buttons.jet
- site/templates/bundle/item.jet
- site/templates/collection/carousel_item.jet
- site/templates/film/item.jet
- site/templates/tv/detail.jet
The purpose of this branch is to relocate the trailer, wishlist and share buttons, to beside the purchase and play buttons. In both the carousel, and detail pages.
This is a managable step towards implementing the [refreshed designs](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/62030a7db4a419bfc4e8371e).
Attention has been on consistent spacing between each button (accounting for elements not always present), gutter alignment, element wrapping at smaller viewports, and element vertical alignment.
[AB#5001](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=5001)
> Relocate the trailer/wishlist/share buttons beside the play/rent/buy buttons. Adjust styling.

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/ee_EE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/se_SE.all.json
- site/templates/film/item.jet
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
#AB3859 - Captions appearing as subtitles: updated item.jet to split out captions and subtitles and display them separately, 
updated all translations files to use new "meta_detail_captions" translation key, place holders are subtitle string + [CC] as that symbol seems universal eg: fr-FR `"meta_detail_subtitles": { "other": "Sous-titres" },
"meta_detail_captions": { "other": "Sous-titres [CC]" `
> Added captions translation + split CC and Subs

- CHANGELOG.md
- kibble.json
- package-lock.json
- package.json
- site/templates/film/item.jet
- upgrade to Kibble 0.16.6, which introduces ImageMap for film objects (in parallel with Images but does not care what they are called)
- references to film.Images changed to film.ImageMap
- update changelog
> Ab#5032 use image map for films

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/ee_EE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/templates/common/awards/item.jet
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO Cards [AB#7080](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=7080) & [AB#7079](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=7079)
The expected behaviour is film displays result_display_label or category display_label if it is not a winner.
> AB#7080: remove additional texts from display label

- CHANGELOG.md
- site/styles/_variables.scss
1. The `$cookie-consent-*` vars were missing `!default` so couldn't override them.
2. Reformatted a bit of the changelog.
> Allow overriding of the cookie consent variables

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/ee_EE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/se_SE.all.json
- site/styles/_meta-detail.scss
- site/templates/film/item.jet
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
This PR:
- Adds component that toggles between Short/Long description divs via button
- does nothing unless `"element_switcher_enabled" = "true"`
- must point to the latest version of relish to work
- Also please view the changes below with GitHub diff setting 'ignore whitespace'
[AB#4745](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=4745)
> S72 element switcher

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/ee_EE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
TLDR: this PR just re-indents all the language json files
- We have now [merged a script into core-template](https://github.com/shift72/core-template/pull/294) that automatically translates a key for each translation file
- A side effect of this was all translations had to be auto formatted as it [rewrites the JSON with two indents](https://github.com/shift72/core-template/blob/develop/scripts/translate.mjs#L39)
- So @stajs [requested a PR](https://github.com/shift72/core-template/pull/295#issuecomment-1076942648) that does the formatting in one fell swoop
- Should theoretically be no different apart from intents/newlines, but cast your eyes over it just in case
> format translations for auto translate script

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/ee_EE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
- Wording was "show more" and "show less"
- which was at odds with signed-off designs
- affects all translations
> AB#7489 Change wording to 'see more' & 'see less'

- site/templates/application/application.jet
- site/templates/application/google.jet
Ok, so ive removed the block / yield to load the GA4 async script and wrote it as an anonymous function instead, so its only loaded once the cookie consent has been checked. Ive tested it locally thoroughly, switching between Legacy GA and GA4 to make sure data is collected and only if cookie consent has been given. I've also tested that the GA4 code works alongside google tag manager.
> Ab#6719   load ga4 script dynamically

- site/templates/film/item.jet
`</div>` seems to have no matching `<div>`, removed
> removed unmatched div

- site/styles/_shift72.scss
As per [AB#7775](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/7775) fix "Blue outline is showing after any of the Share Modal options are selected"
Using a fix that doesnt break screen readers:
https://css-tricks.com/the-focus-visible-trick/
> rm outline on click respecting screen readers

- site/styles/_carousel.scss
- site/templates/collection/carousel_item.jet
- site/templates/common/sponsor-image.jet
In a [previous PR](https://github.com/shift72/core-template/pull/320) we added sponsor images to a film detail page. This PR adds this to carousel also.
- upload a 'sponsor' type image to a film to see it (point template to staging-store.shift72.com a couple already uploaded)
- also set custom field: "sponsor_image_text_film" to add text above it
- [AB#5032](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=5032)
- [Designs](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6209be832a8eafa8366b818c)
> add sponsor logo image carousel

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
[ADO card](https://dev.azure.com/S72/SHIFT72/_workitems/edit/7861)
Change the wording in the share modal from "Link copied to clipboard!" to "Link copied" (and the relevant translations)
> AB#7681 Change wording in share modal

- site/styles/_meta-sub-item.scss
**TLDR: stylelint moved some code, broke bonus/episodes style. Move back and add lint ignore rule.**
- I forgot to add an ignore to stylelint, so when someone else ran it, it moved a media query ([commit](
https://github.com/shift72/core-template/commit/59ddbd13#diff-8621f91c695f61e8fd0f3a81890fd5251371d9eacabd842ed490500ad5403e45R9-R29
)) to above the code it was targeting, making the media query overridden, resulting in layout issues. This PR moves the code back and adds an ignore.
Note: I had to just use /* stylelint-disable */ sorry - couldn't find the exact stylelint rule that moves the code block.
> Fix issue caused by linter moving media query

- CHANGELOG.md
- site/styles/_buttons.scss
- site/styles/_carousel.scss
- site/styles/_meta-sub-item.scss
ADO card: ☑️ [AB#8222](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8222)
Problem:
The new sub-item CSS is order-dependant and it breaks when the linter runs (at least it did before a linter disabling rule was added).
Solution:
Trust that the linter knows best and refactor the CSS to not be order-dependant.
> quick refactor and lint

- .github/workflows/node.js.yml
Bump node version to 16 in `node.js.yml` to stop `npm ci` failing in github actions.
> bump node version in CI

- CHANGELOG.md
- site/templates/bundle/extras.jet
- site/templates/collection/carousel/item/extras.jet
- site/templates/common/social-media-buttons.jet
- site/templates/film/item.jet
- site/templates/tv/detail.jet
ADO card: ☑️ [AB#8128](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=8128)
- [❌] Has this been discussed with Delivery Team?
- Currently the share modal "shares" the current URL (i.e. `window.location.href`)
- This means clicking the share modal from the homepage carousel shares the homepage URL to Facebook, Twitter etc
- Support for an explicit attribute "path" in the ShareModal component has been introduced into Relish (under review)
- Template function `socialMediaButtons` had support for passing a path into the social media buttons but it wasn't used for anything
- Pass this path into the share modal
- If this is empty or missing it falls back to `window.location.href` in the component
- Update …
> AB#8128 Pass explicit paths into share modals

- CHANGELOG.md
- site/styles/_meta-sub-item.scss
- site/templates/items/sub_item.jet
ADO card: ☑️ [AB#8102](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8102)
Designs: 
- 📱 [Mobile](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142ba83fd3fd250f50e6216)
- 💊 [Tablet](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142baeda13fc726053e405a)
- 🖥 [Desktop](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142bb2eb8582a2b4c2c93ee)
- At some point s72-playback-progress was removed from template
- This pr just adds it to bonus/episodes, adds style for height and color
> re-add playback-progress, add css from relish and adjust to design

- site/styles/_meta-detail.scss
ADO card: ☑️ [AB#8287](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8287)
The max-width was removed from `meta-detail-content` on film-detail pages when the s72-element-switcher was added. It resulted in titles being the full width of the screen. This work adds the max-width back in.
> Max width fix

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/templates/items/tagline.jet
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#XXXX](https://dev.azure.com/S72/SHIFT72/_workitems/edit/7964)
~~Elab notes/AC: 📃 [Google Docs](https://docs.google.com)~~
Bundle taglines show n films despite containing tv seasons
Change to use "n items"
Nope
Nope
> AB#7964-generalise bundle tagline for n items

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#8427](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8427)
Add a language string for shopping_card_update_reason_expired to appear in update credit card details modal.
For now this is the same as the message in shopping_card_update_reason_none but may change
> AB#8427 Add language string for shopping_card_update_reason_expired

- CHANGELOG.md
- site/styles/_can-be-watched-button.scss
Not sure if it's intentional, but the can-be-watched button has a heavier font weight than the play button next to it.
This PR makes it normal weight to match the regular button styling. It seemed like this might have just been some copypasta styles that got overlooked when the button styling was changed.
Please close if this was the design intent.
Before:
After:
> Tweak:  change CanBeWatchedButton font weight to match play button

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#8719](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=8719)
"Success!" needs to be marked up as larger than the rest of the message to match designs. Removed from this translation string. Images of changes in related PR.
https://github.com/indiereign/shift72-web/pull/325/files
> AB#8719 remove success from message

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#8875](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8875)
Shopping session modal only checked if item is a plan, then assigned a language string for being a subscription. Added a check for plan type and added/modified the language strings in the core template.
- Site needs plans
- [Relish](https://github.com/indiereign/shift72-web/pull/329)
- Clients with SVOD without the new language string
> Seperate ownership_plan, owership_subscription

- CHANGELOG.md
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/styles/_meta-detail.scss
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#8093](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8093)
Designs: 
- 📱 [Mobile](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/62030a7ff375ab015a507fad)
- ~Makes detail page pricing buttons full width on xs breakpoint~ this PR is now just translations
- Changes translation "Play now" to "Watch now"
- All new clients who use Kibble
> Detail page mobile - CTA button adjustments

- site/styles/_awards.scss
- site/styles/_meta-detail.scss
- site/styles/_typography.scss
ADO card (headings): ☑️ [AB#8089](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8089)
Designs: 
- 🖥 [typography designs section](https://zpl.io/amxOMBr)
- 🖥 [Desktop/tablet](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/61231fda5d02ef1252e998e7)  (font stylesheet)
- 📱 [Mobile](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/61232090efca7116d70899fe)  (font stylesheet)
Carry out design feedback - listed in [this doc](https://docs.google.com/document/d/1EJlDKaCQ7PIDVE3P_dPo6e765CkYVQPZro7v4m9FEgQ), (ignore sections titled spacing, todo in another card): 
- make some adjustments to the headings 
- apply subtitle-1-style to awards
- apply body-1-style to sponsor text
- [] Updated changelog (if applicable)
> design typography adjustments

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#8677](https://dev.azure.com/S72/SHIFT72/_workitems/edit/8677)
- [] Has this been discussed with Delivery Team? - No
Designs: 
[Preliminary Designs in Figma](https://www.figma.com/file/wVniCXFhnwvOw2KzvslHdW/Plans?node-id=519:18872) 
(Arabic)
(English)
Add translations for subscription recurrence on purchase CTAs
> AB#8677: add translations for subscription recurrence on purchase CTAs

- CHANGELOG.md
- site/styles/_icons.scss
ADO card: ☑️ [AB#9171](https://dev.azure.com/S72/SHIFT72/_workitems/edit/9171)
Fixes spinner icon not rotating
Spinner was tested working at time of PR creation https://github.com/shift72/core-template/pull/303. But I forgot to remove font awesome import.
So during the PR I made a [commit ](https://github.com/shift72/core-template/pull/303/commits/df4a7cfa0fa2e9a98620cfed8d4dd8753bb1269c#diff-d634b86743ea9bf5ae117a93030b6adf7329c124a57e4e1738f666cc3816b336L7) to remove it.
This commit inadvertantly removed display: inline-block from `.fa` resulting in animation not being applied to the icon.
Any client since PR was merged (29 April) https://github.com/shift72/core-template/pull/303 and then core-template release mid-may
Sorry guys!
> fix spinner not rotating

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#9319](https://dev.azure.com/S72/SHIFT72/_workitems/edit/9319)
Theres a few translations missing for SVOD, [which we default to English](https://github.com/indiereign/shift72-web/blame/fe7a6b5f1dadc8f9030ed03d9a756195bbfdc0cc/src/transactional/subscriptions/user-subscription.component.js#L135), which isn't great for our international customers. Since we aren't using the site_api_translation yet for filmicca, I've added them here.
> Missing translations for SVOD

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/plans.html.jet
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/subscriptions.html.jet
- site/templates/application/nav/nav.jet
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#9329](https://dev.azure.com/S72/SHIFT72/_workitems/edit/9329)
Elab notes/AC: 📃 [Google Docs](https://docs.google.com/document/d/11svAR84B4KcYdYIQju41HlQXsMgeXq9r8tZKoDuN_QE/edit#heading=h.bny0ht7u7uqz)
- [☑️ ] Has this been discussed with Delivery Team?
Split out translation keys that were used by Core-template and Relish to remove overlapping usage. Updated .jet files to use the core-template specific keys
> Translations relish split

- CHANGELOG.md
- site/templates/application/application.jet
ADO card: ☑️ [AB#8757](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/8757)
Pages don't render properly on iOS versions earlier than 13 because of a missing polyfill for Intl.PluralRules
Version 2.0 of the polyfill doesn't include (support?) specifically this object so upgrade to v3 seems to do it.
I've checked this works on an iOS simulator using versions 12.4, 14.5 and 15.5 of the operating system.
> Ab#8757 change polyfill

- CHANGELOG.md
- site/plans.html.jet
This seems to be the only use of '.Interval' in the .jet files
ADO card: ☑️ [AB#9282](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9282)
The interval of a plan isn't translated into other languages from the plans.html page (viz "monat" vs "month")
- #410 (already merged so translations will exist)
- SVOD clients using languages other than English with recurring plans
> AB#9282 User correct translation for intervals in the templates

- site/da_DK.all.json
- site/pt_BR.all.json
ADO card: ☑️ [AB#9449](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9449)
2 languages have not had `shopping_card_new_subscription` translated
> AB#9449 Correctly translate shopping_card_new_subscription

- CHANGELOG.md
- site/templates/collection/carousel/carousel.jet
ADO card: ☑️ [AB#9140](https://dev.azure.com/S72/SHIFT72/_workitems/edit/9140)
Added support for carousel play speed and fade time configs.
- carousel_play_speed (default is 4000).
- carousel_fade_time (default is 700).
> carousel play speed and fade time config support

- CHANGELOG.md
- site/styles/_meta-detail.scss
ADO card: ☑️ [AB#9272](https://dev.azure.com/S72/SHIFT72/_workitems/edit/9272)
Replaced flex-gap usage on film detail page with grid-gap as flex-gap is not supported on Safari iOS <14.5.
> Ab#9272 remove flex gap usage from film detail page

- CHANGELOG.md
- site/search.html.jet
ADO card: ☑️ [AB#9487](https://dev.azure.com/S72/SHIFT72/_workitems/edit/9487)
Allow us to enable cloud search via feature toggle rather than a custom jet file. I've run it up locally against https://www.maorinow.com/ to check the toggle works on / off.
Meta > Feature Toggles: cloudsearch
> Use feature toggle to enable cloudsearch AB#9487

- CHANGELOG.md
- kibble.json
- package-lock.json
- package.json
- Add new variables to change the font sizes and letter spacing of headings, subtitles, body text, etc.
- Add translations for intervals without counts
- New keys for translations that were used by Relish and Core-template removing their overlapping usage
- Add translation for `shopping_error_card_not_supported`, `shopping_error_processing_error` and `shopping_error_invalid_session_token`
- Added support for self-service CSS and brand images.
- Added support for carousel_play_speed and carousel_fade_time configs.
- Added support to toggle on cloudsearch via Meta > cloudsearch feature toggle.
- Moved the carousel availability label above the CTA's.
- The site url in kibble.json now points to [tvoddemo.shift72.com](https://tvoddemo.shift72.com).
- Full width background image and gradient on …
> release-1.4.0

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#9680](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9680)
Some error messages returned by the discounts API don't have translations. Once we've agreed upon these I'll add them to Curzon.
- All clients who use Kibble and have discounts enabled
> AB#9680 Missing translations

- CHANGELOG.md
- site/pt_BR.all.json
ADO card: ☑️ [AB#9692](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9692)
Designs: 
- 📱 [Mobile](http://www.zeplin.io/????)
- 💊 [Tablet](http://www.zeplin.io/????)
- 🖥 [Desktop](http://www.zeplin.io/????)
Fixed a typo in the Brazilian Portuguese translation shopping_complete_rental.
> Corrected Brazilian Portuguese shopping_complete_rental translation

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/styles/_shopping.scss
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#9743](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9743)
Elab notes/AC: 📃 [Google Docs](https://docs.google.com/document/d/1xVECgmuo5F5HxacMQQUDC3wXsbcCdOQyExJbL28B00Y/edit#heading=h.l6k7fw26aplf)
Adds translations and tiny bit of CSS for live event purchase flow.
- https://github.com/indiereign/shift72-web/pull/350
> live event purchase flow translations and css

- CHANGELOG.md
- site/styles/_availability-tags.scss
- site/styles/_cta-buttons.scss
ADO card: ☑️ [AB#9805](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9805)
- Made it so inline cta buttons now grow when text is wider than button width
- Applies to pricing button, play button, and can be watched button.
> Ab#9805 buttons are not dynamic so text overruns

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#9668](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9668)
Added translations for credit card expiry date validations.
- https://github.com/indiereign/shift72-web/pull/352
> Ab#9668 credit card validation message

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#9935](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9935)
More credit card validation error translations.
> shopping_error_stripe_invalid_number

- CHANGELOG.md
- site/styles/_availability-tags.scss
- site/styles/_meta-detail.scss
- site/templates/bundle/item.jet
ADO card: ☑️ [AB#9825](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9825)
Noticed yesterday a bundle page style regression, just want to add a fix
Bundle page should look like:
https://staging-event.shift72.com/bundle/the-matrix-trilogy/
Currently looks like:
https://staging-store-kibble.shift72.com/bundle/super-bundle/
> fix bundle page

- CHANGELOG.md
- site/templates/tv/detail.jet
ADO card: ☑️ [AB#9938](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9938)
Added poster wrapper element on tv detail page to un-break the layout and match the film detail page layout.
> fixed broken tv detail page layout

- CHANGELOG.md
- site/templates/collection/carousel/item.jet
- site/templates/common/cta_buttons.jet
ADO card: ☑️ [AB#8701](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/8701)
If a trailer button (inside a CTA buttons component) is rendered within the carousel, disable the autoplay if the querystring '?autoplay' is provided, to stop multiple modals with trailers opening up.
Alternatively a solution could lie in Relish, if the s72PlayerModal component looked for multiple such components and not respond to autoplay requests if there's more than one of them on the page. 🤷
> AB#8701 Don't autoplay trailer when in carousel

- CHANGELOG.md
- site/styles/_awards.scss
- site/templates/film/item.jet
ADO card: ☑️ [AB#10063](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/10063)
Designs: https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b?seid=6343624823578b179d193e35
The designs changed again, have to move the awards back to where they were and adjust margin to designs.
> mv award categories on detail page, adjust margin

- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/en_AU.all.json
- site/et_ET.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/pt_PT.all.json
- site/uk_UA.all.json
Make the default footer branding consistent to be Shift72 / www.shift72.com
> clean up branding

- CHANGELOG.md
- site/styles/_meta-detail.scss
ADO card: ☑️ [AB#10213](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/10213)
As per card, the 50px gap is unnecessary at smaller widths.
> AB#10213 Element switcher wrapper

- CHANGELOG.md
- site/styles/_meta-detail.scss
- site/templates/tv/detail.jet
ADO card: ☑️ [AB#10630](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/10630)
Removed extra/unwanted container around episodes from tv detail jet so content no longer gets squashed.
Also ran the CSS linter.
> fixed episode container issue

- kibble.json
ADO card: ☑️ [AB#7318](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/7318)
I'm not clear on why this bug wasn't occurring when running a site locally but was occurring on staging.  Also not clear on why the tvItem urlPath didn't have a trailing slash because the other routes do.  But adding that trailing slash in seems to fix the issue.  Tested on staging-store-kibble clicking links to tv season pages and to specific episodes... both seem to work fine.
Credit goes to Louis for pointing me at the Lonely Planet repo where I spotted this trailing slash discrepancy.
> add trailing slash to tv season url path

- CHANGELOG.md
- site/templates/items/tagline.jet
ADO card: ☑️ [AB#10786](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/10786)
Setting runtime to 60 mins shows as 0m on frontend, this fix ensures if 60 mins is entered, then it will show the hour.
> AB#10786 fix runtime showing as 0m for 1 hour

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/styles/_forms.scss
- site/styles/_shift72.scss
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#10996](https://dev.azure.com/S72/SHIFT72/_workitems/edit/10996)
This PR is part of xxxx Relish PR to add in support for showing a UI to clients with the `validate_email` feature toggle enabled that will bypass the shopping modal sign in flow since it does not support verifying email addresses for sign up.
> AB#10996 Add styles for the relish auth selector

- CHANGELOG.md
- site/styles/_buttons.scss
- site/styles/_nav.scss
ADO card: ☑️ [AB#11220](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11220)
found a couple of cases of border-radius: 50% which works fine with square buttons but goes oval if you have custom button widths. tested both fixes locally.
> AB#11220 fix border radius 50%

- CHANGELOG.md
- site/templates/application/google.jet
ADO card: ☑️ [AB#11072](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11072)
Refactor how we initialise the google scripts / functions for collecting traffic and ecommerce data. The ecommerce data is sent via relish https://github.com/indiereign/shift72-web/pull/426
I've changed the logic slightly so it only loads GTM if theres a GTM code, and initialised the gtag function globally
- May break clients existing setups with ecommerce data sent to GTM and forward on to UA, but this will be unsupported end of June anyway and clients should be upgrading to GA4
- Client needs google admin toggle for it to show the settings to set GA / GTM tracking codes, and have either of those setup.
https://github.com/indiereign/shift72-web/pull/426
- All clients with GA …
> AB#11072 GA refactor

- CHANGELOG.md
- site/signin.html.jet
ADO card: ☑️ [AB#11274](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11274)
Add a config that allows us to hide or change the forgot password link for SSO clients. Config can be set to either "hide" or a url to modify the forgotpassword link, otherwise it will keep the default path. Context: For new SSO with integrated IDP there will simply be the button or a redirect on the signin page so we can just hide it in those cases. For proxy shared accounts, client require to change the url to link off to their sites to change password (like on docedge https://vc.docedge.nz/signin.html) so we can edit the url for those clients also. 
Note: ive used one config to both hide or change the url. We separate these if its nicer - feature toggle for hide forgot password …
> add config to hide or change forgot password link

- CHANGELOG.md
- site/templates/application/nav/user_logged_in.jet
ADO card: ☑️ [AB#11422](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11422)
Add a config that allows us to hide or change the "My Account" link in the user subnav for SSO clients. Config can be set to either "hide" or a url to modify the my account link, otherwise it will keep the default path. Context: For new SSO with integrated IDP accounts are managed on their side, meaning the My Account page will not work, name / password will need to be updated on the client side. For proxy shared accounts, client require to change the url to link off to their sites to change password (like on docedge https://vc.docedge.nz/signin.html) so we can edit the url for those clients also.
Note: ive used one config to both hide or change the url. We separate these if its …
> AB#11422 hide or modify my account from user menu via new config

- CHANGELOG.md
- site/authpass.html.jet
ADO card: ☑️ [AB#11453](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11453)
Elab notes/AC: 📃 [Google Docs](https://docs.google.com/document/d/1z8rWGsEWWkk4jDiIzpVA399_zEM5WVoMRiLqkbBFFsA/edit)
Designs: 
- 📱 [Mobile](https://cdn.dribbble.com/users/58639/screenshots/3788063/936.jpg)
- 💊 [Tablet](https://cdn.dribbble.com/users/58639/screenshots/3788063/936.jpg)
- 🖥 [Desktop](https://cdn.dribbble.com/users/58639/screenshots/3788063/936.jpg)
A trampoline for bouncing auth tokens from Ferve into our site from a different domain. Creates a new page that can be embedded in the background with an iframe, which can pass the auth token in via hash segment of the url, which then gets added to local storage for the domain of the Shift site.
- Sitelock blocks it, for …
> Ab#11453 token trampoline

- CHANGELOG.md
- site/templates/common/cta_buttons.jet
ADO card: ☑️ [AB#11677](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11677)
Feature toggle to not show the letterboxd option in the share modal.
- User > config: show_letterboxd_share (public)
>  AB#11677 config to disable letterboxd share

- kibble.json
- site/templates/application/application.jet
Support for using the Shift72 Checkout.
If toggled on (users > use_checkout) it will slip in a script tag for the checkout launcher. There's a change in relish that will show the checkout rather than new purchase flow if this toggle is on.
To support local dev, I've added a `checkoutDevMode` variable at the top of application.jet. 
- https://github.com/indiereign/shift72-web/pull/434
- Hopefully nobody, behind a feature toggle
> S72 Checkout local dev support

- site/theme.json.jet
This is a temporary feature that can go away once we have a proper theming API.
- theme_primary_color / theme_mode: these are temporary and should get checkout theming working
-  The checkout theming support one
> Add `theme.json.jet`: rudimentary checkout theming support

- CHANGELOG.md
- README.md
- site/templates/application/application.jet
ADO card: ☑️ [AB#11872](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Core%20team/Stories/?workitem=11872)
- Tidies up the checkout embed. Adds flags for local dev checkout and relish rather than commenting/uncommenting nonsense
- Use the new Shift72CheckoutOptions object
- Pass through some helpful URLs that should have the right language codes baked into them.
- It's behind the checkout toggle so shouldn't affect non-checkout sites
- https://github.com/indiereign/shift72-checkout/pull/40
- Testing sites using checkout
> Update checkout embed, and some dev mode niceties in application.jet

- site/ar_LB.all.json
- site/ca_ES.all.json
- site/confirmdelete.html.jet
- site/da_DK.all.json
- site/de_DE.all.json
- site/deleteresult.html.jet
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/styles/_forms.scss
- site/styles/_pages.scss
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#11812](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11812)
Adds in a page that will let a user confirm their account deletion, which they will be directed to from an email, and then a page to put them on after this has been triggered. I haven't really handled error cases... I also don't know how to do the translation stuff so still a bit of work to do here. 
- Users -> Feature toggle -> user_deletion set to is enabled for the apis to work.
https://github.com/indiereign/shift72-web/pull/442
https://github.com/indiereign/shift72-users/pull/416
https://github.com/indiereign/shift72-users/pull/412
> pages to handle user self deletion story

- site/templates/items/meta_item.jet
The can-be-watched-button is visible to logged out users if the film is flagged as available to watch (Such as if the film is in a free plan and the disable_anonymous_watch_now toggle is not enabled). We're limiting this to only logged in users.
> Hid live event button for logged out users

- CHANGELOG.md
- kibble.json
- package.json
- site/styles/_carousel.scss
- site/styles/_pages.scss
- site/templates/collection/carousel/item/image.jet
ADO card: ☑️ [AB#12169](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/12169)
Checks if carousel image focus area has been set for a carousel item and applies a class to fix the image to the left / right center. 
- Kibble: https://github.com/shift72/kibble/pull/138
- Admin: https://github.com/indiereign/shift72-admin/pull/890 (to allow admins to set the carousel image focus area on film / seasons / pages / bundles).
> Ab#12169 add carousel focus from tv / film objects to position carousel image

- site/theme.json.jet
I have updated Checkout to support many new theming options. Part of this changes the names of the primary color and color mode. 
`primaryColor` -> `colorPrimary`
The theme variables were based off Stripes theme variables. I liked prefixing the colors with `color` and the suffix was the thing the color related to. It also made it easy to map from the theme to Stripe's theme.
`mode` -> `colorScheme`
This change was to match what Mantine called the light/dark toggle.  I felt it was more specific.
I've also updated the default color scheme to be `dark`. This is because most of our sites are dark.
This release needs to go out before we can roll Checkout out to production.
> Update the theme to support new version of Checkout theme

- CHANGELOG.md
- site/ar_LB.all.json
- site/ca_ES.all.json
- site/da_DK.all.json
- site/de_DE.all.json
- site/el_EL.all.json
- site/en_AU.all.json
- site/es_ES.all.json
- site/es_MX.all.json
- site/et_ET.all.json
- site/fi_FI.all.json
- site/fr_FR.all.json
- site/hr_HR.all.json
- site/hu_HU.all.json
- site/it_IT.all.json
- site/ja_JP.all.json
- site/lt_LT.all.json
- site/nl_BE.all.json
- site/no_NO.all.json
- site/pl_PL.all.json
- site/pt_BR.all.json
- site/pt_PT.all.json
- site/ru_RU.all.json
- site/sr_SR.all.json
- site/static/js/main.js
- site/templates/collection/continue_watching.jet
- site/templates/page/homepage.jet
- site/tr_TR.all.json
- site/uk_UA.all.json
- site/zh_TW.all.json
ADO card: ☑️ [AB#XXXX](https://dev.azure.com/S72/SHIFT72/_workitems/edit/12307)
- Think this is going to be an easy couple of hours tops, it's basically just the wishlist with a different data source right
- See the extent of the hacks but get to work refactoring
- ???
- ...Profit?
- Config `continue_watching = true`. Figured this is the kind of thing we might want to just make admin-configurable.
- Related configs in Relish can control max items and max age of items that get shown.
- https://github.com/indiereign/shift72-web/pull/453
This feature will be most valuable to SVOD and AVOD clients, but it could be turned on for TVOD clients too.
> Continue watching slider

- site/templates/application/application.jet
Refs https://sansec.io/research/polyfill-supply-chain-attack
polyfill.io CDN has released polyfilljs version with malware. This change is to use the Cloudflare CDN as they are more reputable. This is a short term fix, long term we need to move away from using a 3rd party CDN for this issue (along with GDPR compliance).
> Use cloudflare CDN for polyfill.js to avoid supply chain risk

- site/styles/_collections.scss
- site/styles/_library.scss
- site/styles/_wishlist.scss
Collection views had a negative margin hack that was causing grid rows to not line up -- it was adding -5px margin to the first child of the collection to counteract the 5px padding to align the poster with the titles, but this caused subsequent rows to be misaligned.
I've also tweaked the caption padding to move the text closer to the poster.  This makes the visual grouping clearer when there are multiple rows -- the text used to sit awkwardly close to the middle.
Another fix was adding a max-width to the library and wishlist pages to avoid the items spreading out if you have a really wide window.
> Alignment fix ups for sliders/collections/library pages

- site/styles/_nav.scss
It looked even worse when there is no language selector
Old:
New:
> Fix visual centering of the magnifying glass icon

- CHANGELOG.md
- kibble.json
- site/styles/_meta-item-title.scss
- site/styles/_variables.scss
- site/styles/main.scss
- site/templates/collection/carousel/item.jet
- site/templates/collection/carousel/item/title.jet
- site/templates/film/item.jet
- site/templates/items/title.jet
Uses existing custom image type for films so that a title image can be added into admin for upload with the other images. 
Create a generic title jet so i can be used both on the carousel and detail page. this will load in the image if it exists, else just use the existing heading.
Sets image as fixed width with a max height in an attempt to keep it within a desirable location. The custom image types are defined per site in uber, so have set these as variables to allow for simplifying some flexibility if for some reason a client had a custom size to display. 
Looking at custom image type support for film, there would be some substantial work to extend this to pages / tv etc, so scope is just for films at the moment.
Initial PR for feedback / thoughts on where from here.
> Film title images

- CHANGELOG.md
- site/templates/collection/carousel/item/video.jet
Noticed when testing in Firefox that it shows some pretty obnoxious picture in picture UI if you don't disable it.
> Disable picture in picture for carousel video

- CHANGELOG.md
- site/styles/_globals.scss
- site/styles/_legacy.scss
- site/styles/_meta-item-tagline.scss
- site/styles/_nav.scss
- site/styles/_typography.scss
- site/styles/_variables.scss
New
Old
Add global `-webkit-font-smoothing: antialiased` and disabled font synthesis (prevents Safari from generating hideous looking fake bold fonts if styles use a weight that isn't available.
Tweaked the poster styling so that the meta tagline is more subtle.
> Typography Tweaks

- CHANGELOG.md
- package.json
- site/styles/_carousel.scss
- site/styles/_collections.scss
- site/styles/_detail-player.scss
- site/styles/_meta-item.scss
- site/styles/_poster.scss
- site/styles/_search.scss
- site/styles/_swiper.scss
- site/styles/_typography.scss
- site/styles/_variables.scss
Adds a skeleton and proper sizing for posters before the images load in.
This prevents collection pages from collapsing down to only show a bunch of titles, and also just looks less broken as the pages load.
The skeleton colour can be controlled with the `--poster-skeleton-background-color` variable
The expected poster aspect ratio is set with CSS variables but only affects the placeholders -- once the image loads, the aspect-ratio rule is removed.
In order to get the responsive sizing right, I've changed meta items to use flex-column layout. 
Adding skeletons revealed some jank with swipers -- the slides would momentarily be huge (100% width basically) because it relies on the Swiper library calculating the widths in JS.
To fix this, I've hidden the sliders  and set a max-height until …
> De-janking poster / collection loading

- CHANGELOG.md
- site/styles/_meta-detail.scss
- site/templates/film/item.jet
> remove extra space before , in cast list; tweak link underline css
